- PolicySet:
    hosts:
    - localhost
    name: Check for mysql package installation
    policies:
    - Policy:
        actions:
        - Action:
            action: deny
            action_args:
              msg: The package {{ input["ansible.builtin.package"].name }} is not
                allowed, allowed packages are one of {{ allowed_packages }}
        condition:
          AllCondition:
          - ItemNotInListExpression:
              lhs:
                String: input["ansible.builtin.package"].name
              rhs:
                String: allowed_packages
        enabled: true
        name: Check for package name
        tags:
        - compliance
        target: task
    vars:
      allowed_packages:
      - mysql-server
