# package-example.yml
---
- name: Check for mysql package installation
  hosts: localhost # decision environment (can be a container) vars:
  allowed_packages:
    - mysql
  ## Define the conditions we are looking for
  rules:  # need to support policies: in ast.py
    - name: Check for package name
      # condition: input["ansible.bultin.package"].name not in allowed_packages
      condition: module == "custom.unauthorized.package"
      actions:
        - deny:
            msg: The package {{ module }} is not allowed
      tags:
        - compliance
  sources: {}  # error if missing