# package-example.yml
---
- name: Check for using module
  hosts: localhost # decision environment (can be a container) 
  vars:
    allowed_modules:
      - mysql
      - ansible.builtin.set_fact
      - ansible.builtin.file
  ## Define the conditions we are looking for
  policies:
    - name: Check for module name
      # condition: input["ansible.builtin.package"].name not in allowed_packages
      condition: input.task.module not in allowed_modules ## Define the action we should take should the condition be met 
      actions:
        - deny:
            msg: The package {{ input.task.module }} is not allowed, allowed modules are one of {{ allowed_modules }}
      tags:
        - compliance