- PolicySet:
    hosts:
    - localhost
    name: Check for insecure file permission
    policies:
    - Policy:
        actions:
        - Action:
            action: deny
            action_args:
              msg: file permission is insecure, recommended permissions are {{ recommended_permissions
                }}.
        condition:
          AnyCondition:
          - ItemInListExpression:
              lhs:
                String: input["ansible.builtin.file"].mode
              rhs:
                String: insecure_file_permission
          - ItemInListExpression:
              lhs:
                String: input["ansible.builtin.copy"].mode
              rhs:
                String: insecure_file_permission
          - ItemInListExpression:
              lhs:
                String: input["ansible.builtin.template"].mode
              rhs:
                String: insecure_file_permission
        enabled: true
        name: Check for insecure file permission
        tags:
        - compliance
        target: task
    vars:
      insecure_file_permission:
      - '1777'
      recommended_permissions:
      - '0755'
