- PolicySet:
    hosts:
    - localhost
    name: Check for file permission
    policies:
    - Policy:
        actions:
        - Action:
            action: deny
            action_args:
              msg: The file permission {{ input["ansible.builtin.file"].mode }} is
                not allowed
        condition:
          AllCondition:
          - NotEqualsExpression:
              lhs:
                String: input["ansible.builtin.file"].mode
              rhs:
                String: '"444"'
        enabled: true
        name: Check for file change
        tags:
        - compliance
        target: task
    vars: {}
