- hosts: localhost
  vars:
    package_name: "check_become_policy"
    filepath: "/tmp/{{ package_name }}.rego"
  tasks:
    - gatekeeper.rego.rule:
        name: become_true_task
        exprs:
          - input.task.become.enabled
          - task_name = input.task.name
        return: task_name
      register: become_true_task

    - gatekeeper.rego.check:
        name: using_become
        exprs:
          - become_true_task != ""
      register: using_become

    - gatekeeper.rego.transform:
        filepath: "{{ filepath }}"
        package_name: "{{ package_name }}"
        tags:
          - compliance
        match:
          - module: "*"
        compose:
          - "{{ become_true_task }}"
          - "{{ using_become }}"
