# package-example.yml
---
- name: Restrict instances with unapproved AMIs
  hosts: localhost 
  vars:
    allowed_image_ids:
      - ami-123456
      - ami-789011
  policies:
    - name: Restrict instances with unapproved AMIs
      target: task
      condition: input["amazon.aws.rds_instance"].image_id not in allowed_image_ids
      actions:
        - deny:
            msg: The image {{ input["amazon.aws.rds_instance"].image_id}} is not allowed, allowed images are one of {{ allowed_image_ids }}
      tags:
        - compliance