### check insecure file permission policy ###
# This policybook prohibit using sticky bit as a file permission.
# If the mode option for a task using the ansible.built-in.file module is 1777, a violation will be detected.
---
- name: Check for insecure file permission
  hosts: localhost 
  vars:
    insecure_file_permission:
    - "1777" # sticky bit
    recommended_permissions:
    - "0755"
  policies:
    - name: Check for insecure file permission
      target: task
      condition: 
        any:
        - input["ansible.builtin.file"].mode in insecure_file_permission
        - input["ansible.builtin.copy"].mode in insecure_file_permission
        - input["ansible.builtin.template"].mode in insecure_file_permission
      actions:
        - deny:
            msg: file permission is insecure, recommended permissions are {{ recommended_permissions }}.
      tags:
        - compliance
